import './globals.css'
import { poppins } from './fonts';
import { Suspense } from 'react';
import Loading from './loading';

export const metadata = {
  title: 'Titulo padrão',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main>
          <h1>Teste</h1>
          <Suspense fallback={<Loading/>}>
            {children}
          </Suspense>
        </main>
      </body>
    </html>
  )
}
