import './globals.css'
import { poppins } from './fonts';
import { Suspense } from 'react';
import Loading from './loading';
import NavBar from '@/components/navBar';

export const metadata = {
  title: 'Titulo padrão',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NavBar />
        <main>
          <h1>Netflix com um título grande</h1>
          {children}
        </main>
      </body>
    </html>
  )
}
