import './globals.css'
import { poppins } from './fonts';

export const metadata = {
  title: 'Titulo padrão',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
